version: '3'
services:
  verdaccio:
    container_name: verdaccio
    # build: ./
    image: verdaccio/verdaccio:4.x-next
    ports:
      - '4873:4873'
    restart: always
    environment:
      PORT: 4873
    volumes:
      - ./conf:/verdaccio/conf 
      - ./storage:/verdaccio/storage 
      - ./plugins:/verdaccio/plugins 
volumes:
  verdaccio:
    driver: local
